### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by dfmjndm** [Starrah/BilibiliGetDynamics#2]
Traceback (most recent call last):
  File "c:\Users\11619\Documents\py\bilidy.py", line 68, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "D:\python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\Users\11619\Documents\py\bilidy.py", line 55, in main
    cardObj = cardToObj(card)
  File "c:\Users\11619\Documents\py\bilidy.py", line 32, in cardToObj
    "item": getItem(input["card"]["item"]),
KeyError: 'item'

**Comment by Starrah** [comment]
麻烦您提供下爬取的用户的UID吧，我明天排查一下

**Comment by dfmjndm** [comment]
394936，我刚刚才看到你在readme里写的最后一句话，改成直接输出card，就可以跑了。

**Comment by Starrah** [comment]
好的，谢谢您
应该是有card的类型没有判断全，有的card没有"item"字段造成的。我明天优化一下。
