### ISSUE TITLE
没见过的问题，麻烦帮我看看

### ISSUE THREAD

**Issue by Ulery** [Starrah/BilibiliGetDynamics#5]
Traceback (most recent call last):
  File "getDynamics.py", line 116, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "getDynamics.py", line 106, in main
    print(cardStr)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f338' in position 323: illegal multibyte sequence

**Comment by Ulery** [comment]
有没有直接在网页操作的方法
